network: mainnet
workspace: boxd
database:
    name: memdb
log:
    out:
        name: stderr # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box.log
              maxlines: 100000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  4 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    key_path: networkkey
    port: 19199
    bucket_size: 16
    latency: 10
rpc:
    port: 19191
    http:
        port: 19190
dpos:
    index: 0
    pubkey: e34cce70c86373273efcc54ce7d2a491bb4a0e84