log:
    out:
        name: stderr # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: file
          options:
              filename: box.log
              maxlines: 100000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  2 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug

# node:
#     addpeer: [multiaddr]
#     listen:
#         port: 19199
#         address: 127.0.0.1
p2p:
    magic: 0x11de784a
    key_path: networkkey
    port: 19199
    bucket_size: 16
    latency: 10
