network: mainnet
workspace: boxd2
database:
    name: memdb
log:
    out:
        name: stderr # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box.log
              maxlines: 100000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  4 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    magic: 0x11de784a
    port: 19197
    seeds:
        - "/ip4/0.0.0.0/tcp/19199/ipfs/12D3KooWAfLnAMKm7MwnpwBN8aEbAVFxZcw4uUaAjMcv6xehmrFg"
    bucket_size: 16
    latency: 10
rpc:
    port: 19171
    http:
        port: 19170
dpos:
    index: 10
    pubkey: 0af020217fd26e0b6bf40912bca223b1dd806a21