network: mainnet
workspace: boxd1
database:
    name: rocksdb
log:
    out:
        name: stderr # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box.log
              maxlines: 100000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  4 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    key_path: peer.key
    port: 19198
    seeds:
        - "/ip4/127.0.0.1/tcp/19199/ipfs/12D3KooWAfLnAMKm7MwnpwBN8aEbAVFxZcw4uUaAjMcv6xehmrFg"
    bucket_size: 16
    latency: 10
rpc:
    port: 19181
    http:
        port: 19180
dpos:
    index: 5
    pubkey: 0ef030107fd26e0b6bf40512bca2ceb1dd80adaa