version: "3.3"

services:
  node_1:
    image: boxd:latest
    command: "./box start --config=./.devconfig/.box-1.yaml"
    #deploy:
    #  replicas: 1
    #    resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #  restart_policy:
    #    condition: none
    ports:
      - "19199:19199"
      - "19191:19191"
      - "19190:19190"
    volumes:
      - ./.devconfig:/app/boxd/.devconfig
    networks:
      boxdnet:
        ipv4_address: 172.27.1.11

  node_2:
    image: boxd:latest
    command: "./box start --config=./.devconfig/.box-2.yaml"
    ports:
      - "19189:19189"
      - "19181:19181"
      - "19180:19180"
    volumes:
      - ./.devconfig:/app/boxd/.devconfig
    networks:
      boxdnet:
        ipv4_address: 172.27.1.12

  node_3:
    image: boxd:latest
    command: "./box start --config=./.devconfig/.box-3.yaml"
    ports:
      - "19179:19179"
      - "19171:19171"
      - "19170:19170"
    volumes:
      - ./.devconfig:/app/boxd/.devconfig
    networks:
      boxdnet:
        ipv4_address: 172.27.1.13

networks:
  boxdnet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24
