version: "3"

services:
  box1:
    image: jerrypeen/boxd:latest
    environment:
      - "TZ=Asia/Shanghai"
    command:
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime &&
      echo $TZ > /etc/timezone &&
      ./box start --config=./.devconfig/.box-1.yaml"
    ports:
      - "19199:19199"
      - "19111:19111"
      - "19110:19110"
    volumes:
      - ./.devconfig:/app/boxd/.devconfig
    networks:
      boxdnet:
        ipv4_address: 172.27.1.11

networks:
  boxdnet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.1.0/24
