network: mainnet
workspace: .devconfig/ws1
database:
    name: rocksdb
log:
    out:
        name: null # stdout|stderr|null
    level: warning # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box1.log
              maxlines: 10000000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  5 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    key_path: peer.key
    port: 19199
    bucket_size: 16
    latency: 10
    conn_max_capacity: 200
    conn_load_factor: 0.8
    relay_size: 32
rpc:
    port: 19111
    http:
        port: 19110
    faucet:
        keyfile: ./.devconfig/keyfile/pre.keystore
        ip_list:
            - 192.168.21.255
            - 192.168.21.76
            - 127.0.0.1
    subscribe_blocks: true
    subscribe_logs: true

bpos:
    keypath: key.keystore
    enable_mint: true
    passphrase: 1

pprof: "0.0.0.0:8888"

metrics:
    enable: false
    host: http://localhost:8086
    db: box
    user: 
    password:
    tags: [region:us-west, host:box-1]
wallet:
    enable: true
    cache_size: 512
    utxo_cache_time: 1
