network: mainnet
workspace: .devconfig/ws15
database:
    name: rocksdb
log:
    out:
        name: stderr # stdout|stderr|null
    level: warning # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box15.log
              maxlines: 10000000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  5 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    key_path: peer.key
    port: 19059
    seeds:
        - "/ip4/127.0.0.1/tcp/19139/p2p/12D3KooW9zwdCPaaHarsJ9H2boX6KbnTDGsx3WN6G1onHB8zjvqQ"
    bucket_size: 16
    latency: 10
    conn_max_capacity: 200
    conn_load_factor: 0.8
    relay_size: 32
rpc:
    port: 19251
    http:
        port: 19250
    subscribe_blocks: true
    subscribe_logs: true
bpos:
    keypath: key.keystore
    enable_mint: false
    passphrase: 1
metrics:
    enable: true
    host: http://localhost:8086
    db: box
    user: 
    password: 
    tags: [region:us-west, host:box-15]
wallet:
    enable: true
    cache_size: 512
    utxo_cache_time: 1
