network: mainnet
workspace: .devconfig/ws1
database:
    name: rocksdb
log:
    out:
        name: null # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box1.log
              maxlines: 10000000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  5 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    key_path: peer.key
    port: 19199
    agents:
        - "/ip4/127.0.0.1/tcp/19139/p2p/12D3KooW9zwdCPaaHarsJ9H2boX6KbnTDGsx3WN6G1onHB8zjvqQ"
    bucket_size: 16
    latency: 10
    conn_max_capacity: 200
    conn_load_factor: 0.8
    relay_size: 32
rpc:
    enable: true
    address: 0.0.0.0
    port: 19111
    http:
        address: 0.0.0.0
        port: 19110
    faucet:
        amount_per_sec: 1000000000000
        keyfile: ./.devconfig/keyfile/pre.keystore
        white_list:
            - "*"
            - "127.0.0.1"
    subscribe_blocks: true
    subscribe_logs: true
    admin_ips:
      - "127.0.0.1"

bpos:
    keypath: key.keystore
    enable_mint: true
    passphrase: 1

pprof: "0.0.0.0:8888"

metrics:
    enable: false
    host: http://localhost:8086
    db: box
    user: 
    password:
    tags: [region:us-west, host:box-1]
wallet:
    enable: true
    utxo_cache_time: 1
