network: mainnet
workspace: .devconfig/ws7
database:
    name: rocksdb
log:
    out:
        name: stderr # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box.log
              maxlines: 100000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  5 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    address: 0.0.0.0
    port: 19139
    seeds:
        # - "/ip4/127.0.0.1/tcp/19199/p2p/12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza"
        - "/ip4/127.0.0.1/tcp/19189/p2p/12D3KooWKPRAK7vBBrVv9szEin55kBnJEEuHG4gDTQEM72ByZDpA"

        # - "/ip4/39.105.210.220/tcp/19009/p2p/12D3KooWPGai3zWoov6LfRLCAqqd3BDSp7i7p2wXCvpBsptMUDDS"
        # - "/ip4/39.105.210.220/tcp/19129/p2p/12D3KooWKPRAK7vBBrVv9szEin55kBnJEEuHG4gDTQEM72ByZDpA"
        # - "/ip4/39.105.210.220/tcp/19139/p2p/12D3KooWSdXLNeoRQQ2a7yiS6xLpTn3LdCr8B8fqPz94Bbi7itsi"
        # - "/ip4/39.105.214.10/tcp/19149/p2p/12D3KooWRHVAwymCVcA8jqyjpP3r3HBkCW2q5AZRTBvtaungzFSJ"
        # - "/ip4/39.105.214.10/tcp/19159/p2p/12D3KooWQSaxCgbWakLcU69f4gmNFMszwhyHbwx4xPAhV7erDC2P"
        # - "/ip4/39.105.214.10/tcp/19169/p2p/12D3KooWNcJQzHaNpW5vZDQbTcoLXVCyGS755hTpendGzb5Hqtcu"
    bucket_size: 16
    latency: 10
    conn_max_capacity: 200 
    conn_load_factor: 0.8
rpc:
    port: 19131
    http:
        port: 19130
    subscribe_blocks: true
    subscribe_logs: true
dpos:
    enable_mint: false
metrics:
    enable: true
    host: http://localhost:8086
    db: box
    user: 
    password: 
    tags: [region:us-west, host:box-7]
