network: mainnet
workspace: .devconfig/ws3
database:
    name: rocksdb
log:
    out:
        name: stderr # stdout|stderr|null
    level: debug # debug|info|warning|error|fatal
    formatter:
        name: text # json|text
    hooks:
        - name: filewithformatter
          options:
              filename: box.log
              maxlines: 100000
              # daily: true
              # maxsize: 10240000
              rotate: true
              level:  4 # 0:panic, 1:fatal, 2:error, 3:warning, 4:info, 5:debug
p2p:
    key_path: peer.key
    port: 19179
    seeds:
        - "/ip4/127.0.0.1/tcp/19199/p2p/12D3KooWFQ2naj8XZUVyGhFzBTEMrMc6emiCEDKLjaJMsK7p8Cza"
    bucket_size: 16
    latency: 10
rpc:
    port: 19171
    http:
        port: 19170
dpos:
    index: 10
    pubkey: 0af020217fd26e0b6bf40912bca223b1dd806a21